

-- goods�뀒�씠釉붿뿉 gStock(�옱怨�) �빆紐� 異붽�
ALTER TABLE goods
add gStock VARCHAR(20);

-- Notice(怨듭��궗�빆) �뀒�씠釉� �깮�꽦
create table Notice
(  num NUMBER(6) PRIMARY KEY,
    writeDay DATE  DEFAULT SYSDATE,
    title varchar2(500),
    contents varchar2(3900),
    writer varchar2(500),
    viewcount NUMBER(6)
);   
-- 怨듭��궗�빆 寃뚯떆�뙋 踰덊샇 �떆���뒪 �깮�꽦
create sequence notice_seq;

-- QA(1:1臾몄쓽) �뀒�씠釉� �깮�꽦
create table QA
(  num NUMBER(6) PRIMARY KEY,
    category varchar2(20),
    writeDay DATE  DEFAULT SYSDATE,
    title varchar2(500),
    contents varchar2(3900),
    userid  varchar2(20)
);   
   
alter table QA
add CONSTRAINT QA_userid_fk FOREIGN KEY(userid)
REFERENCES member(userid) ON DELETE CASCADE;

-- 1:1臾몄쓽 寃뚯떆�뙋 踰덊샇 �떆���뒪 �깮�꽦
create sequence QA_seq;

-- QA(1:1臾몄쓽) �뀒�씠釉� �떟蹂� �냽�꽦 異붽�
ALTER TABLE QA
add answer VARCHAR(3900);


-- Notice공지사항 더미데이터
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항1', '공지사항1입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항2', '공지사항2입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항3', '공지사항3입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항4', '공지사항4입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항5', '공지사항5입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항6', '공지사항7입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항8', '공지사항8입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항9', '공지사항9입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항10', '공지사항10입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항11', '공지사항11입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항12', '공지사항12입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항13', '공지사항13입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항14', '공지사항14입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항15', '공지사항15입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항16', '공지사항16입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항17', '공지사항17입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항18', '공지사항18입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항19', '공지사항19입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항20', '공지사항20입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항21', '공지사항21입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항22', '공지사항22입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항23', '공지사항23입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항24', '공지사항24입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항25', '공지사항25입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항26', '공지사항26입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항27', '공지사항27입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항28', '공지사항28입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항29', '공지사항29입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항30', '공지사항30입니다', '관리자', 0 );
COMMIT;